// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAHpgAvDpHCyHflNDbQg3_V1Y_dzfG5i8',
    appId: '1:375830810171:web:b7f4685c5753ac4932561e',
    messagingSenderId: '375830810171',
    projectId: 'brainibot-90126',
    authDomain: 'brainibot-90126.firebaseapp.com',
    storageBucket: 'brainibot-90126.appspot.com', // <--- CAMBIADO
    measurementId: 'G-3NYWKKZRL5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNwqZOwQna7RyLXVzeFd23GmzRyuURL4I',
    appId: '1:375830810171:android:5bc831d88ac17e9332561e',
    messagingSenderId: '375830810171',
    projectId: 'brainibot-90126',
    storageBucket: 'brainibot-90126.firebasestorage.app', // <--- CAMBIADO
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsr-zZrLYBgAN7n2f5dps8yOPzdzReqy8',
    appId: '1:375830810171:ios:c835d5cb11cbc3ae32561e',
    messagingSenderId: '375830810171',
    projectId: 'brainibot-90126',
    storageBucket: 'brainibot-90126.firebasestorage.app', // <--- CAMBIADO
    iosBundleId: 'com.example.brainibot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsr-zZrLYBgAN7n2f5dps8yOPzdzReqy8',
    appId: '1:375830810171:ios:c835d5cb11cbc3ae32561e', // Nota: appId aquí suele ser distinto para macOS si se configura explícitamente
    messagingSenderId: '375830810171',
    projectId: 'brainibot-90126',
    storageBucket: 'brainibot-90126.firebasestorage.app', // <--- CAMBIADO
    iosBundleId: 'com.example.brainibot', // Nota: macOS suele tener su propio bundleId
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAHpgAvDpHCyHflNDbQg3_V1Y_dzfG5i8',
    appId: '1:375830810171:web:dcaf0321f953ad4232561e', // Nota: appId aquí suele ser distinto para Windows si se configura explícitamente
    messagingSenderId: '375830810171',
    projectId: 'brainibot-90126',
    authDomain: 'brainibot-90126.firebasestorage.app',
    storageBucket: 'brainibot-90126.appspot.com', // <--- CAMBIADO
    measurementId: 'G-LL8LP9BJ47',
  );
}